### ISSUE TITLE
Add exchanges view

### ISSUE THREAD

**Issue by mastercyb** [asadovka/cyb_web2#30]
One of the most important objects has been forgotten 🥇 
Should be on the main menu

**Comment by cyborgshead** [comment]
Will be migrated to cyber-desing for design/analytics.

**Comment by abitrolly** [comment]
@21xhipster am I right that we need at least a page with a list of supported exchanges. Then which info should we list in order of priority?

I am personally interested in our internal metrics for data collectors (connectors):
1. Time gap since last trade
2. Exchange data quality level (https://github.com/cyberFund/cyber-markets/issues/49)
3. Market uptime
4. Missing data

**Comment by cyborgshead** [comment]
Exchange view added to left menu, work with concept of this page will start at next milestone.

**Comment by cyborgshead** [comment]
First draft-mockup on the way to team analytics
